### ISSUE TITLE
254 - Button to calculator not working in Get Started

### ISSUE THREAD

**Issue by Clearviction** [openseattle/clearviction-next#37] opened 2023-03-18 00:04 UTC
> This issue was created using an Airtable automation. If there is information missing from the issue, more information may be available in the Airtable record, linked below.
## Airtable Record URL
https://airtable.com/appfJZShN8K4tcWHU/tblvBIYoi6TLmdRAv/recTyqiVdwxo438fT
## Information
- Site URL - https://clearviction-next.vercel.app/get-started#step-2
- Browser - safari
## Description 
The button that takes you to the calculator in "Step 2:Eligibility" is broken, it leads to 404 error. -Judit

**Comment by e-papanicolas** [comment] 2023-03-18 01:03
Duplicate of 253.

**Closed** 2023-03-18 01:04 UTC
